# Generated by Django 3.1 on 2020-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrabbleWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Scrabble Dictionary',
                'verbose_name_plural': 'Scrabble Dictionary',
                'ordering': ['word'],
            },
        ),
    ]
