# Generated by Django 3.1 on 2020-08-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrabbleword',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
