# Generated by Django 3.1 on 2020-08-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scrabbleword_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrabbleword',
            options={'ordering': ['word', 'score'], 'verbose_name': 'Scrabble Dictionary', 'verbose_name_plural': 'Scrabble Dictionary'},
        ),
    ]
